kind: Service
apiVersion: v1
metadata:
  name: hasher-canary-service
spec:
  type: NodePort
  selector:
    app: hasher-canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasher-deployment-canary
  labels:
    app: hasher-canary
spec:
  replicas: __REPLICAS__
  selector:
    matchLabels:
      app: hasher-canary
  template:
    metadata:
      labels:
        app: hasher-canary
    spec:
      containers:
      - name: hasher
        image: mbouzayeni/hasher:__TAG__
        ports:
        - containerPort: 80
      nodeSelector:
        app: test 