name: Dockercoins CI/CD hasher component
run-name: Dockercoins hasher CI/CD
on: [push]
jobs:
  Test:
    name: Run Unit Tests.
    runs-on: ubuntu-latest
    working-directory: hasher
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Unit Test Hasher Ruby
      run: |
        ruby hasher/tests/unit_test.rb
  BuildScanAndPushImage:
    name: Build and push the docker image.
    runs-on: ubuntu-latest
    working-directory: hasher
    permissions: write-all
    needs: Test
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get current version
        id: get_current_version
        run: |
          current_version=$(cat VERSION)
          echo "currentVersion=$(cat VERSION)" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.get_current_version.outputs.currentVersion }}
          release_name: Release ${{ steps.get_current_version.outputs.currentVersion }}
          body: |
            Hasher version ${{ steps.get_current_version.outputs.currentVersion }}.
          draft: false
          prerelease: false  
      - name: Set current branch
        id: current_branch
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      - name: Calculate image tag
        id: calculate_tag
        run: |
          currentBranch=${{ steps.current_branch.outputs.branch }}
          if [[ $currentBranch == 'main' ]]
            then
              tag=${{ steps.get_current_version.outputs.currentVersion }}
          else
            tag=${{ steps.get_current_version.outputs.currentVersion }}-${{ github.sha }}
          fi   
          echo "tag=$tag" >> $GITHUB_OUTPUT 
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            mbouzayeni/hasher:${{ steps.calculate_tag.outputs.tag }}
          cache-from: type=registry,ref=mbouzayeni/hasher:buildcache
          cache-to: type=registry,ref=mbouzayeni/hasher:buildcache,mode=max
  # DeployCanary:
  # DeployToProduction: