name: Dockercoins CI/CD reids component
run-name: Dockercoins redis CI/CD
on: [push]
env:
  CLUSTER: dockercoins-cluster
  CLUSTER_ZONE: europe-west1-b
  PROJECT_NAME: playground-s-11-937fc184
  TEST_NODE_IP: "34.140.19.46"
  TEST_PORT: 30003

jobs:
  BuildScanAndPushImage:
    name: Build and push the docker image.
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: redis_server
    permissions: write-all
    steps:
      
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get current version
        id: get_current_version
        run: |
          current_version=$(cat VERSION)
          echo "currentVersion=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.get_current_version.outputs.currentVersion }}
          release_name: Release ${{ steps.get_current_version.outputs.currentVersion }}
          body: |
            Hasher version ${{ steps.get_current_version.outputs.currentVersion }}.
          draft: false
          prerelease: false

      - name: Get current branch
        id: current_branch
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Calculate image tag
        id: calculate_tag
        run: |
          currentBranch=${{ steps.current_branch.outputs.branch }}
          if [[ $currentBranch == 'main' ]]
            then
              tag=${{ steps.get_current_version.outputs.currentVersion }}
          else
            tag=${{ steps.get_current_version.outputs.currentVersion }}-${{ github.sha }}
          fi   
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v4
        with:
          file: redis_server/Dockerfile
          push: true
          tags: |
            mbouzayeni/redis:${{ steps.calculate_tag.outputs.tag }}
          cache-from: type=registry,ref=mbouzayeni/hasher:buildcache
          cache-to: type=registry,ref=mbouzayeni/hasher:buildcache,mode=max
    outputs:
      imageTag: ${{ steps.calculate_tag.outputs.tag }}

  Test:
    name: Run Smoke Tests.
    runs-on: ubuntu-latest
    needs: BuildScanAndPushImage
    defaults:
      run:
        working-directory: redis_server
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Install gcloud authentication plugin
      run: |
        REPO_URL="https://packages.cloud.google.com/apt"
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] $REPO_URL cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list >/dev/null
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

        sudo apt-get update -y
        sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

    - name: Authenticate to GKE cluster
      env:
        GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
      run: |   
        echo "$GCLOUD_KEY" > ${HOME}/gcloud.json
        gcloud auth activate-service-account --key-file=${HOME}/gcloud.json
        gcloud container clusters get-credentials \
        ${{ env.CLUSTER_NAME }} --zone ${{ env.CLUSTER_ZONE }} --project ${{ env.PROJECT_NAME }}

    - name: copy the manifest file
      run: |
        cp redis-canary-manifest.yml redis-canary-manifest-delete.yml

    - name: Update the image tag & the number of canary replicas to 1
      uses: cschleiden/replace-tokens@v1
      with:
        files: '["redis_server/redis-canary-manifest.yml"]'
        tokenPrefix: __
        tokenSuffix: __
      env:
        TAG: ${{ needs.BuildScanAndPushImage.outputs.imageTag }}
        REPLICAS: 1

    - name: Deploy to the gke cluster
      run: kubectl apply -f redis-canary-manifest.yml

    - name: Replace the URI in the test file
      uses: cschleiden/replace-tokens@v1
      with:
        files: '["redis_server/tests/smoke_test.py"]'
        tokenPrefix: __
        tokenSuffix: __
      env:
        URI: "'${{ env.TEST_NODE_IP }}'"
        PORT: ${{ env.TEST_PORT }}

    - name: Run Smoke tests
      run: |
        pip install pytest redis
        pytest

    - name: Update image tag & the number of canary replicas to 0 to delete it
      uses: cschleiden/replace-tokens@v1
      with:
        files: '["redis_server/redis-canary-manifest-delete.yml"]'
        tokenPrefix: __
        tokenSuffix: __
      env:
        TAG: ${{ needs.BuildScanAndPushImage.outputs.imageTag }}
        REPLICAS: 0
         
    - name: Delete redis-canary
      run: kubectl apply -f redis-canary-manifest-delete.yml